name: Push to Main

on:
  push:
    branches: [main, develop]

jobs:
  test_and_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        branch: [main, develop]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.1.1
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test

      - name: Build project
        run: pnpm run build

      - name: Semantic Release (for develop)
        if: ${{ matrix.branch == 'develop' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --branches develop

      - name: Semantic Release (for production)
        if: ${{ matrix.branch == 'main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
