name: Release Develop

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.1
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    needs: test
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.1
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Archive develop artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-develop-artifact
          path: lib

  release:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: develop
      url: https://npmjs.com/package/commit-toolbox
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.1
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Download develop artifact
        uses: actions/download-artifact@v2
        with:
          name: release-develop-artifact
          path: lib

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Release Develop
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run release:develop -- --ci
